# Your Name or Company
title: Welcome to the MR Card Game.
# Description of your website. This is used for social sharing.
description:  A Mixed Reality-Based Card Game for Formal and Informal Education.

# A brief blurb about yourself
content: MR Card Game is an educational, customizable AR (Augmented Reality) tower defense card game application that allows for playful learning by combining quiz questions with engaging real-time strategy gameplay. The goal of the game is to defend your castle against approaching attackers by casting spells, setting traps and building powerful defensive towers to slow down the invaders. In order to gain access to these defenses, players need to answer questions from a chosen field or topic. If answered correctly, players can use varying cards to defeat wave after wave of a wide variety of attackers.

# Add your social links
social:
  - platform: github
    url: https://github.com/brianmaierjr
  - platform: facebook
    url: https://facebook.com/brianmaierjr
  - platform: twitter
    url: https://twitter.com/brianmaierjr
  - platform: linkedin
    url: brianmaierjr

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: half-md.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
